# Generated by Django 3.2.3 on 2021-06-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homename', models.CharField(max_length=40, verbose_name='Названия номера')),
            ],
        ),
    ]
