# Generated by Django 3.2.3 on 2021-06-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='homes',
            new_name='home',
        ),
    ]
