# Generated by Django 3.2.3 on 2021-06-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_homes_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='homer',
        ),
    ]
